services:
  nestjs_api:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - '3500:3500'
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=nestjs_content_creator_server
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307
  frontend:
    build: ./front
    container_name: front
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
    stdin_open: true
    tty: true